### ISSUE TITLE
pytests  and test directories

### ISSUE THREAD

**Issue by jacksonhenry3** [jacksonhenry3/CDT#39]
I noticed that there are some tests in visualization. Should each sub module have its own tests directory. Does pytest run all of these?

**Comment by JWKennington** [comment]
Pytest runs all tests in the package, including subdirectories. There are a couple caveats, the folders must be called "tests" and the files must start with "test_". For example, the new tests you just added in #40 didn't actually run in the build, since the module they are in doesn't start with "test_":

<img width="600" alt="Screen Shot 2021-02-26 at 4 11 17 PM" src="https://user-images.githubusercontent.com/6699803/109355607-74a94f80-784d-11eb-8152-0142b5ced598.png">

**Comment by jacksonhenry3** [comment]
got it, thanks. I didn't intend for the new tests to run. They are more like checks that can be run on a space_time (more in line with audit) but i figured tests was still the right place for them to live.
